import Vue from 'vue'
import { Tree, Icon, Input, Form, FormItem, Button, Upload, Table, Col, Row, TableColumn, Dialog, Tabs, TabPane, Drawer, Container, Main, Switch, Option, DatePicker, Select, Radio, Collapse, CollapseItem, Checkbox } from 'element-ui'
Vue.use(Tree)
Vue.use(Icon)
Vue.use(Input)
Vue.use(FormItem)
Vue.use(Form)
Vue.use(Button)
Vue.use(Upload)
Vue.use(Table)
Vue.use(Col)
Vue.use(Row)
Vue.use(TableColumn)
Vue.use(Dialog)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Drawer)
Vue.use(Container)
Vue.use(Main)
Vue.use(Switch)
Vue.use(Option)
Vue.use(DatePicker)
Vue.use(Select)
Vue.use(Radio)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Checkbox)
